Deliberate failure

diff --git a/.github/workflows/test-git-push.yml b/.github/workflows/test-git-push.yml
--- a/.github/workflows/test-git-push.yml
+++ b/.github/workflows/test-git-push.yml
@@ -68,6 +68,7 @@ jobs:
         run: |
           git config --global user.email "${{ github.actor_id }}+${{ github.actor }}-github-actions[bot]@users.noreply.github.com"
           git config --global user.name "${{ github.actor }}-github-actions[bot]"
+          echo "Failing deliberately to confirm the email step is not executed...!" && exit 1
 
       - name: Send email
         uses: dawidd6/action-send-mail@v3
